const NeverHaveIEver = [
    {
        id: 0,
        title_no: "Jeg har aldri hoppet i fallskjerm.",
        title_en: "Never have I ever gone skydiving.",
        categories: ["Party"],
    },
    {
        id: 1,
        title_no: "Jeg har aldri løyet for en politimann.",
        title_en: "Never have I ever lied to the police.",
        categories: ["Party"],
    },
    {
        id: 2,
        title_no: "Jeg har aldri ligget med en kjendis.",
        title_en: "Never have I ever slept with a celebrity.",
        categories: ["Party", "Wild"],
    },
    {
        id: 3,
        title_no: "Jeg har aldri hatt en trekant.",
        title_en: "Never have I ever had a threesome.",
        categories: ["Party", "Wild"],
    },
    {
        id: 4,
        title_no: "Jeg har aldri snoket i noen andre sine private meldinger.",
        title_en: "Never have I ever snooped through someone else's private messages.",
        categories: ["Party"],
    },
    {
        id: 5,
        title_no: "Jeg har aldri fått sparken fra en jobb.",
        title_en: "Never have I ever been fired from a job.",
        categories: ["Party"],
    },
    {
        id: 6,
        title_no: "Jeg har aldri drukket så mye at jeg besvimte.",
        title_en: "Never have I ever passed out from drinking.",
        categories: ["Party"],
    },
    {
        id: 7,
        title_no: "Jeg har aldri løyet om hvor jeg var til partneren min.",
        title_en: "Never have I ever lied about where I was to my partner.",
        categories: ["Party"],
    },
    {
        id: 8,
        title_no: "Jeg har aldri spyttet i noen annens drink.",
        title_en: "Never have I ever spit in someone else's drink.",
        categories: ["Party", "Wild"],
    },
    {
        id: 9,
        title_no: "Jeg har aldri tatt på meg noens undertøy uten at de visste om det.",
        title_en: "Never have I ever worn someone else's underwear without them knowing.",
        categories: ["Party", "Wild"],
    },
    {
        id: 10,
        title_no: "Jeg har aldri snoket i noen andres medisinskap.",
        title_en: "Never have I ever snooped through someone else's medicine cabinet.",
        categories: ["Party"],
    },
    {
        id: 11,
        title_no: "Jeg har aldri fått en tatovering i beruset tilstand.",
        title_en: "Never have I ever gotten a tattoo while drunk.",
        categories: ["Party"],
    },
    {
        id: 12,
        title_no: "Jeg har aldri hatt sex på en fest.",
        title_en: "Never have I ever had sex at a party.",
        categories: ["Party", "Wild"],
    },
    {
        id: 13,
        title_no: "Jeg har aldri blitt kastet ut av en butikk.",
        title_en: "Never have I ever been kicked out of a store.",
        categories: ["Party"],
    },
    {
        id: 14,
        title_no: "Jeg har aldri kranglet med en fremmed i offentligheten.",
        title_en: "Never have I ever argued with a stranger in public.",
        categories: ["Party"],
    },
    {
        id: 15,
        title_no: "Jeg har aldri sovet i en bil.",
        title_en: "Never have I ever slept in a car.",
        categories: ["Party"],
    },
    {
        id: 16,
        title_no: "Jeg har aldri blitt dumpet via en tekstmelding.",
        title_en: "Never have I ever been dumped via text message.",
        categories: ["Party"],
    },
    {
        id: 17,
        title_no: "Jeg har aldri sovnet på en datamaskin.",
        title_en: "Never have I ever fallen asleep at the computer..",
        categories: ["Party"],
    },
    {
        id: 18,
        title_no: "Jeg har aldri blitt tatt i å røyke.",
        title_en: "Never have I ever been caught smoking.",
        categories: ["Party"],
    },
    {
        id: 19,
        title_no: "Jeg har aldri fyllekjørt med sykkel.",
        title_en: "Never have I ever ridden a bike while drunk.",
        categories: ["Party", "Wild"],
    },
    {
        id: 20,
        title_no: "Jeg har aldri kysset noen jeg ikke var tiltrukket av.",
        title_en: "Never have I ever kissed someone I wasn't attracted to.",
        categories: ["Party", "Wild"],
    },
    {
        id: 21,
        title_no: "Jeg har aldri sovet gjennom en hel dag.",
        title_en: "Never have I ever slept through an entire day.",
        categories: ["Party"],
    },
    {
        id: 22,
        title_no: "Jeg har aldri blitt kastet ut av et casino.",
        title_en: "Never have I ever been kicked out of a casino.",
        categories: ["Party", "Gaming"],
    },
    {
        id: 23,
        title_no: "Jeg har aldri løyet om å være syk for å få fri fra jobb.",
        title_en: "Never have I ever lied about being sick to get out of work.",
        categories: ["Party"],
    },
    {
        id: 24,
        title_no: "Jeg har aldri glemt navnet på noen jeg lå med.",
        title_en: "Never have I ever forgotten the name of someone I slept with.",
        categories: ["Party", "Wild"],
    },
    {
        id: 25,
        title_no: "Jeg har aldri lurt noen til å tro at jeg kunne et annet språk.",
        title_en: "Never have I ever tricked someone into thinking I knew another language.",
        categories: ["Party"],
    },
    {
        id: 26,
        title_no: "Jeg har aldri brukt noen andres tannbørste.",
        title_en: "Never have I ever used someone else's toothbrush.",
        categories: ["Party"],
    },
    {
        id: 27,
        title_no: "Jeg har aldri blitt tatt på fersken i en kompromitterende situasjon.",
        title_en: "Never have I ever been caught in a compromising situation.",
        categories: ["Party"],
    },
    {
        id: 28,
        title_no: "Jeg har aldri ødelagt en bryllupsfest.",
        title_en: "Never have I ever crashed a wedding.",
        categories: ["Party"],
    },
    {
        id: 29,
        title_no: "Jeg har aldri prøvd å kaste opp for å føle meg bedre.",
        title_en: "Never have I ever tried to throw up to feel better.",
        categories: ["Party", "Wild"],
    },
    {
        id: 30,
        title_no: "Jeg har aldri kastet opp med vilje for å bli mindre full.",
        title_en: "Never have I ever thrown up on purpose to drink more.",
        categories: ["Party", "Wild"],
    },
    {
        id: 31,
        title_no: "Jeg har aldri kastet opp med vilje for så å drikke mer.",
        title_en: "Never have I ever thrown up on purpose to drink more.",
        categories: ["Party", "Wild"],
    },
    {
        id: 32,
        title_no: "Jeg har aldri hatt en affære med en kollega.",
        title_en: "Never have I ever had an affair with a coworker.",
        categories: ["Party", "Wild"],
    },
    {
        id: 33,
        title_no: "Jeg har aldri blitt tatt i å snike på offentlig transport.",
        title_en: "Never have I ever been caught sneaking on public transportation.",
        categories: ["Party"],
    },
    {
        id: 34,
        title_no: "Jeg har aldri stjålet noe fra en restaurant.",
        title_en: "Never have I ever stolen something from a restaurant.",
        categories: ["Party"],
    },
    {
        id: 35,
        title_no: "Jeg har aldri stjålet noe fra et utested.",
        title_en: "Never have I ever stolen something from a bar.",
        categories: ["Party"],
    },
    {
        id: 36,
        title_no: "Jeg har aldri kysset en eks etter at vi slo opp.",
        title_en: "Never have I ever kissed an ex after we broke up.",
        categories: ["Party"],
    },
    {
        id: 37,
        title_no: "Jeg har aldri blitt oppdaget naken.",
        title_en: "Never have I ever been caught naked.",
        categories: ["Party", "Wild"],
    },
    {
        id: 38,
        title_no: "Jeg har aldri spyttet ut mat jeg ikke likte i en serviett.",
        title_en: "Never have I ever spit out food I didn't like into a napkin.",
        categories: ["Party"],
    },
    {
        id: 39,
        title_no: "Jeg har aldri prøvd å lure en bouncer på en klubb.",
        title_en: "Never have I ever tried to trick a bouncer at a club.",
        categories: ["Party", "Wild"],
    },
    {
        id: 40,
        title_no: "Jeg har aldri sniklyttet på noen andres samtale.",
        title_en: "Never have I ever eavesdropped on someone else's conversation.",
        categories: ["Party"],
    },
    {
        id: 41,
        title_no: "Jeg har aldri brukt en falsk ID.",
        title_en: "Never have I ever used a fake ID.",
        categories: ["Party"],
    },
    {
        id: 42,
        title_no: "Jeg har aldri mistet mobilen min på en fest.",
        title_en: "Never have I ever lost my phone at a party.",
        categories: ["Party"],
    },
    {
        id: 43,
        title_no: "Jeg har aldri blitt fanget i å lyve på jobb.",
        title_en: "Never have I ever been caught lying at work.",
        categories: ["Party"],
    },
    {
        id: 44,
        title_no: "Jeg har aldri mistet noen på et utested.",
        title_en: "Never have I ever lost someone at a bar.",
        categories: ["Party"],
    },
    {
        id: 45,
        title_no: "Jeg har aldri hatt sex på et sted med risiko for å bli oppdaget.",
        title_en: "Never have I ever had sex in a place where I could get caught.",
        categories: ["Party", "Wild"],
    },
    {
        id: 46,
        title_no: "Jeg har aldri kastet opp på noen.",
        title_en: "Never have I ever thrown up on someone.",
        categories: ["Party"],
    },
    {
        id: 47,
        title_no: "Jeg har aldri skadet meg selv mens jeg var full.",
        title_en: "Never have I ever hurt myself while drunk.",
        categories: ["Party"],
    },
    {
        id: 48,
        title_no: "Jeg har aldri løyet om hvor jeg har reist på ferie.",
        title_en: "Never have I ever lied about where I went on vacation.",
        categories: ["Party"],
    },
    {
        id: 49,
        title_no: "Jeg har aldri glemt hvor jeg parkerte bilen min.",
        title_en: "Never have I ever forgotten where I parked my car.",
        categories: ["Party"],
    },
    {
        id: 50,
        title_no: "Jeg har aldri tatt med meg noe hjem fra en bar.",
        title_en: "Never have I ever taken something home from a bar.",
        categories: ["Party"],
    },
    {
        id: 51,
        title_no: "Jeg har aldri kysset noen jeg bare hadde kjent i noen timer.",
        title_en: "Never have I ever kissed someone I had only known for a few hours.",
        categories: ["Party", "Wild"],
    },
    {
        id: 52,
        title_no: "Jeg har aldri blitt tatt på fersken i å sjekke noen opp.",
        title_en: "Never have I ever been caught hitting on someone.",
        categories: ["Party", "Wild"],
    },
    {
        id: 53,
        title_no: "Jeg har aldri stjålet en venns partner.",
        title_en: "Never have I ever stolen a friend's partner.",
        categories: ["Party", "Wild"],
    },
    {
        id: 54,
        title_no: "Jeg har aldri blitt kastet ut av et hotell.",
        title_en: "Never have I ever been kicked out of a hotel.",
        categories: ["Party"],
    },
    {
        id: 55,
        title_no: "Jeg har aldri hatt sex på et fly.",
        title_en: "Never have I ever had sex on a plane.",
        categories: ["Party", "Wild"],
    },
    {
        id: 56,
        title_no: "Jeg har aldri blitt kastet ut av en kino.",
        title_en: "Never have I ever been kicked out of a movie theater.",
        categories: ["Party"],
    },
    {
        id: 57,
        title_no: "Jeg har aldri blitt utestengt fra et nettforum.",
        title_en: "Never have I ever been banned from an online forum.",
        categories: ["Party"],
    },
    {
        id: 58,
        title_no: "Jeg har aldri blitt tatt i å lese noen andres dagbok.",
        title_en: "Never have I ever been caught reading someone else's diary.",
        categories: ["Party"],
    },
    {
        id: 59,
        title_no: "Jeg har aldri løyet om min seksuelle erfaring.",
        title_en: "Never have I ever lied about my sexual experience.",
        categories: ["Party", "Wild"],
    },
    {
        id: 60,
        title_no: "Jeg har aldri skulket skolen.",
        title_en: "Never have I ever skipped school.",
        categories: ["Party"],
    },
    {
        id: 61,
        title_no: "Jeg har aldri vært i en situasjon der jeg trodde jeg skulle dø.",
        title_en: "Never have I ever been in a situation where I thought I was going to die.",
        categories: ["Party"],
    },
    {
        id: 62,
        title_no: "Jeg har aldri hatt sex i en heis.",
        title_en: "Never have I ever had sex in an elevator.",
        categories: ["Party", "Wild"],
    },
    {
        id: 63,
        title_no: "Jeg har aldri løyet om inntekten min.",
        title_en: "Never have I ever lied about my income.",
        categories: ["Party"],
    },
    {
        id: 64,
        title_no: "Jeg har aldri stjålet noe fra et hotellrom.",
        title_en: "Never have I ever stolen something from a hotel room.",
        categories: ["Party"],
    },
    {
        id: 65,
        title_no: "Jeg har aldri blitt tatt i å lyve til politiet.",
        title_en: "Never have I ever been caught lying to the police.",
        categories: ["Party"],
    },
    {
        id: 66,
        title_no: "Jeg har aldri hatt sex på en strand.",
        title_en: "Never have I ever had sex on a beach.",
        categories: ["Party", "Wild"],
    },
    {
        id: 67,
        title_no: "Jeg har aldri hatt sex i en bil.",
        title_en: "Never have I ever had sex in a car.",
        categories: ["Party", "Wild"],
    },
    {
        id: 68,
        title_no: "Jeg har aldri hatt sex i et svømmebasseng.",
        title_en: "Never have I ever had sex in a swimming pool.",
        categories: ["Party", "Wild"],
    },
    {
        id: 69,
        title_no: "Jeg har aldri hatt sex i en park.",
        title_en: "Never have I ever had sex in a park.",
        categories: ["Party", "Wild"],
    },
    {
        id: 70,
        title_no: "Jeg har aldri hatt sex med noen jeg ikke likte.",
        title_en: "Never have I ever had sex with someone I didn't like.",
        categories: ["Party", "Wild"],
    },
    {
        id: 71,
        title_no: "Jeg har aldri hatt sex på Huset.",
        title_en: "Never have I ever had sex at Huset.",
        categories: ["Party", "Wild", "NTNU"],
    },
    {
        id: 72,
        title_no: "Jeg har aldri brukt noen andres deodorant uten at de visste om det.",
        title_en: "Never have I ever used someone else's deodorant without them knowing.",
        categories: ["Party"],
    },
    {
        id: 73,
        title_no: "Jeg har aldri blitt forlatt på en dårlig date.",
        title_en: "Never have I ever been left on a bad date.",
        categories: ["Party"],
    },
    {
        id: 74,
        title_no: "Jeg har aldri prøvd å fake en dialekt.",
        title_en: "Never have I ever tried to fake an accent.",
        categories: ["Party"],
    },
    {
        id: 75,
        title_no: "Jeg har aldri snoket i partnerens mobiltelefon.",
        title_en: "Never have I ever snooped through my partner's phone.",
        categories: ["Party"],
    },
    {
        id: 76,
        title_no: "Jeg har aldri sendt en flau melding til feil person.",
        title_en: "Never have I ever sent an embarrassing message to the wrong person.",
        categories: ["Party"],
    },
    {
        id: 77,
        title_no: "Jeg har aldri blitt kastet ut av et bibliotek.",
        title_en: "Never have I ever been kicked out of a library.",
        categories: ["Party"],
    },
    {
        id: 78,
        title_no: "Jeg har aldri spist mat ut av søpla.",
        title_en: "Never have I ever eaten food out of the trash.",
        categories: ["Party"],
    },
    {
        id: 79,
        title_no: "Jeg har aldri blacket ut.",
        title_en: "Never have I ever had a blackout.",
        categories: ["Party"],
    },
    {
        id: 80,
        title_no: "Jeg har aldri blitt oppdaget i å ta en selfie.",
        title_en: "Never have I ever been caught taking a selfie.",
        categories: ["Party"],
    },
    {
        id: 81,
        title_no: "Jeg har aldri prøvd å skjule en tatovering.",
        title_en: "Never have I ever tried to hide a tattoo.",
        categories: ["Party"],
    },
    {
        id: 82,
        title_no: "Jeg har aldri prøvd å kjøre bil mens jeg var for full.",
        title_en: "Never have I ever tried to drive a car while too drunk.",
        categories: ["Party", "Wild"],
    },
    {
        id: 83,
        title_no: "Jeg har aldri gitt en falsk telefonnummer.",
        title_en: "Never have I ever given a fake phone number.",
        categories: ["Party"],
    },
    {
        id: 84,
        title_no: "Jeg har aldri stjålet noe fra en venns hus.",
        title_en: "Never have I ever stolen something from a friend's house.",
        categories: ["Party"],
    },
    {
        id: 85,
        title_no: "Jeg har aldri blitt tatt i å lyve på et jobbintervju.",
        title_en: "Never have I ever been caught lying in a job interview.",
        categories: ["Party"],
    },
    {
        id: 86,
        title_no: "Jeg har aldri prøvd å fake en signatur.",
        title_en: "Never have I ever tried to fake a signature.",
        categories: ["Party"],
    },
    {
        id: 87,
        title_no: "Jeg har aldri stukket av fra en restaurant uten å betale.",
        title_en: "Never have I ever left a restaurant without paying.",
        categories: ["Party"],
    },
    {
        id: 88,
        title_no: "Jeg har aldri blitt kastet ut av en taxi.",
        title_en: "Never have I ever been kicked out of a taxi.",
        categories: ["Party"],
    },
    {
        id: 89,
        title_no: "Jeg har aldri drukket så mye at jeg glemte natten før.",
        title_en: "Never have I ever drank so much that I forgot the night before.",
        categories: ["Party"],
    },
    {
        id: 90,
        title_no: "Jeg har aldri hatt sex på første date.",
        title_en: "Never have I ever had sex on a first date.",
        categories: ["Party", "Wild"],
    },
    {
        id: 91,
        title_no: "Jeg har aldri faket en orgasme.",
        title_en: "Never have I ever faked an orgasm.",
        categories: ["Party", "Wild"],
    },
    {
        id: 92,
        title_no: "Jeg har aldri blitt tatt i å se på porno.",
        title_en: "Never have I ever gotten caught watching porn.",
        categories: ["Party", "Wild"],
    },
    {
        id: 93,
        title_no: "Jeg har aldri prøvd å rømme fra en politibil.",
        title_en: "Never have I ever tried to run away from a police car.",
        categories: ["Party"],
    },
    {
        id: 94,
        title_no: "Jeg har aldri glemt mitt eget telefonnummer.",
        title_en: "Never have I ever forgotten my own phone number.",
        categories: ["Party"],
    },
    {
        id: 95,
        title_no: "Jeg har aldri prøvd å stjele en gatestolpe.",
        title_en: "Never have I ever tried to steal a traffic pole.",
        categories: ["Party"],
    },
    {
        id: 96,
        title_no: "Jeg har aldri blitt fanget i å stalke noen på sosiale medier.",
        title_en: "Never have I ever got caught stalking someone on social media.",
        categories: ["Party"],
    },
    {
        id: 97,
        title_no: "Jeg har aldri blitt tatt i å prøve å kopiere en annens stil.",
        title_en: "Never have I ever been caught trying to copy someone else's style.",
        categories: ["Party"],
    },
    {
        id: 98,
        title_no: "Jeg har aldri mistet klærne mine på en fest.",
        title_en: "Never have I ever lost my clothes at a party.",
        categories: ["Party"],
    },
    {
        id: 99,
        title_no: "Jeg har aldri blitt tatt i å klippe mine egne hår.",
        title_en: "Never have I ever been caught cutting my own hair.",
        categories: ["Party"],
    },
    {
        id: 100,
        title_no: "Jeg har aldri prøvd å bestikke en politimann.",
        title_en: "Never have I ever tried to bribe a police officer.",
        categories: ["Party"],
    },
    {
        id: 101,
        title_no: "Jeg har aldri sovnet på et offentlig sted.",
        title_en: "Never have I ever fallen asleep in a public place.",
        categories: ["Party"],
    },
    {
        id: 102,
        title_no: "Jeg har aldri hatt en sexdrøm om en venn.",
        title_en: "Never have I ever had a sex dream about a friend.",
        categories: ["Party", "Wild"],
    },
    {
        id: 103,
        title_no: "Jeg har aldri sendt en melding til en ex i beruset tilstand.",
        title_en: "Never have I ever sent a message to an ex while drunk.",
        categories: ["Party", "Wild"],
    },
    {
        id: 104,
        title_no: "Jeg har aldri løyet om en familietragedie for å få sympati.",
        title_en: "Never have I ever lied about a family tragedy to get sympathy.",
        categories: ["Party"],
    },
    {
        id: 105,
        title_no: "Jeg har aldri hatt en fantasi om en lærer eller professor.",
        title_en: "Never have I ever had a fantasy about a teacher or professor.",
        categories: ["Party", "Wild", "School"],
    },
    {
        id: 106,
        title_no: "Jeg har aldri vært i fengsel.",
        title_en: "Never have I ever been to jail.",
        categories: ["Party"],
    },
    {
        id: 107,
        title_no: "Jeg har aldri blitt tatt i å se på en annens kropp.",
        title_en: "Never have I ever been caught checking out someone else's body.",
        categories: ["Party", "Wild"],
    },
    {
        id: 108,
        title_no: "Jeg har aldri vært i en slåsskamp.",
        title_en: "Never have I ever been in a fight.",
        categories: ["Party"],
    },
    {
        id: 109,
        title_no: "Jeg har aldri blitt arrestert.",
        title_en: "Never have I ever been arrested.",
        categories: ["Party"],
    },
    {
        id: 110,
        title_no: "Jeg har aldri vært på en one night stand.",
        title_en: "Never have I ever been on a one night stand.",
        categories: ["Party", "Wild"],
    },
    {
        id: 111,
        title_no: "Jeg har aldri tatt narkotika.",
        title_en: "Never have I ever taken drugs.",
        categories: ["Party", "Wild"],
    },
    {
        id: 112,
        title_no: "Jeg har aldri snikdrukket på jobb/skole.",
        title_en: "Never have I ever drank secretly at work/school.",
        categories: ["Party", "School"],
    },
    {
        id: 113,
        title_no: "Jeg har aldri jukset på en prøve.",
        title_en: "Never have I ever cheated on a test.",
        categories: ["Party"],
    },
    {
        id: 114,
        title_no: "Jeg har aldri blitt tatt i å stjele.",
        title_en: "Never have I ever been caught stealing.",
        categories: ["Party"],
    },
    {
        id: 115,
        title_no: "Jeg har aldri hatt sex på et offentlig sted.",
        title_en: "Never have I ever had sex in a public place.",
        categories: ["Party", "Wild"],
    },
    {
        id: 116,
        title_no: "Jeg har aldri fått en bot for å kjøre for fort.",
        title_en: "Never have I ever gotten a speeding ticket.",
        categories: ["Party"],
    },
    {
        id: 117,
        title_no: "Jeg har aldri spilt strippepoker.",
        title_en: "Never have I ever played strip poker.",
        categories: ["Party", "Wild"],
    },
    {
        id: 118,
        title_no: "Jeg har aldri hatt sex med noen jeg ikke visste navnet på.",
        title_en: "Never have I ever had sex with someone whose name I didn't know.",
        categories: ["Party", "Wild"],
    },
    {
        id: 119,
        title_no: "Jeg har aldri sendt nakenbilder av meg selv til noen.",
        title_en: "Never have I ever sent nudes of myself to someone.",
        categories: ["Party", "Wild"],
    },
    {
        id: 120,
        title_no: "Jeg har aldri stjålet noen andres kjæreste.",
        title_en: "Never have I ever stolen someones partner.",
        categories: ["Party"],
    },
    {
        id: 121,
        title_no: "Jeg har aldri spist mat som hadde falt på gulvet.",
        title_en: "Never have I ever eaten food that fell on the floor.",
        categories: ["Party"],
    },
    {
        id: 122,
        title_no: "Jeg har aldri kjørt bil mens jeg var full.",
        title_en: "Never have I ever driven a car while drunk.",
        categories: ["Party"],
    },
    {
        id: 123,
        title_no: "Jeg har aldri tatt en piercing eller tatovering jeg angret på.",
        title_en: "Never have I ever gotten a piercing or tattoo I regret.",
        categories: ["Party"],
    },
    {
        id: 124,
        title_no: "Jeg har aldri hatt en hemmelig beundrer.",
        title_en: "Never have I ever had a secret admirer.",
        categories: ["Party"],
    },
    {
        id: 125,
        title_no: "Jeg har aldri fått en klage på jobb/skole.",
        title_en: "Never have I ever gotten a complaint at work/school.",
        categories: ["Party", "School"],
    },
    {
        id: 126,
        title_no: "Jeg har aldri hatt en one night stand med noen jeg nettopp hadde møtt.",
        title_en: "Never have I ever had a one night stand with someone I just met.",
        categories: ["Party", "Wild"],
    },
    {
        id: 127,
        title_no: "Jeg har aldri vært i et slåsskamp med noen i familien min.",
        title_en: "Never have I ever been in a fight with a family member.",
        categories: ["Party"],
    },
    {
        id: 128,
        title_no: "Jeg har aldri prøvd å flykte fra politiet.",
        title_en: "Never have I ever tried to escape from the police.",
        categories: ["Party"],
    },
    {
        id: 129,
        title_no: "Jeg har aldri vært på en date som var så dårlig at jeg ba om å bli hentet.",
        title_en: "Never have I ever been to a date so bad that I asked to be picked up.",
        categories: ["Party"],
    },
    {
        id: 130,
        title_no: "Jeg har aldri drukket for mye og våknet opp et annet sted enn der jeg skulle.",
        title_en: "Never have I ever drank too much and woke up somewhere else than where I was supposed to.",
        categories: ["Party"],
    },
    {
        id: 131,
        title_no: "Jeg har aldri stjålet fra jobb/skole.",
        title_en: "Never have I ever stolen from work/school.",
        categories: ["Party", "School"],
    },
    {
        id: 132,
        title_no: "Jeg har aldri våknet opp i en fremmed seng.",
        title_en: "Never have I ever woken up in a stranger's bed.",
        categories: ["Party"],
    },
    {
        id: 133,
        title_no: "Jeg har aldri våknet opp i et fremmed hus uten å vite hvor jeg er.",
        title_en: "Never have I ever woken up in a stranger's house without knowing where I am.",
        categories: ["Party", "Wild"],
    },
    {
        id: 134,
        title_no: "Jeg har aldri kysset noen av samme kjønn.",
        title_en: "Never have I ever kissed someone of the same gender.",
        categories: ["Party", "Wild"],
    },
    {
        id: 135,
        title_no: "Jeg har aldri løyet om å ha vært i et forhold.",
        title_en: "Never have I ever lied about being in a relationship.",
        categories: ["Party", "Wild"],
    },
    {
        id: 136,
        title_no: "Jeg har aldri spionert på noen.",
        title_en: "Never have I ever spied on someone.",
        categories: ["Party", "Wild"],
    },
    {
        id: 137,
        title_no: "Jeg har aldri blitt kastet ut av en bar/klubb.",
        title_en: "Never have I ever been kicked out of a bar/club.",
        categories: ["Party"],
    },
    {
        id: 138,
        title_no: "Jeg har aldri hatt sex med noen som var i et forhold.",
        title_en: "Never have I ever had sex with someone who was in a relationship.",
        categories: ["Party", "Wild"],
    },
    {
        id: 139,
        title_no: "Jeg har aldri stjålet noen andres idé.",
        title_en: "Never have I ever stolen someone else's idea.",
        categories: ["Party"],
    },
    {
        id: 140,
        title_no: "Jeg har aldri lurt på om jeg var homofil eller lesbisk.",
        title_en: "Never have I ever wondered if I was gay or lesbian.",
        categories: ["Party"],
    },
    {
        id: 141,
        title_no: "Jeg har aldri hatt sex med noen som var yngre enn meg.",
        title_en: "Never have I ever had sex with someone who was younger than me.",
        categories: ["Party", "Wild"],
    },
    {
        id: 142,
        title_no: "Jeg har aldri jukset på en eksamen.",
        title_en: "Never have I ever cheated on an exam.",
        categories: ["Party", "School"],
    },
    {
        id: 143,
        title_no: "Jeg har aldri ødelagt noe som ikke var mitt.",
        title_en: "Never have I ever broken something that wasn't mine.",
        categories: ["Party"],
    },
    {
        id: 144,
        title_no: "Jeg har aldri kjørt en bil uten å ha gyldig førerkort.",
        title_en: "Never have I ever driven a car without a valid driver's license.",
        categories: ["Party"],
    },
    {
        id: 145,
        title_no: "Jeg har aldri glemt min egen bursdag.",
        title_en: "Never have I ever forgotten my own birthday.",
        categories: ["Party"],
    },
    {
        id: 146,
        title_no: "Jeg har aldri fått en bot for å drikke på offentlig sted.",
        title_en: "Never have I ever gotten a ticket for drinking in public.",
        categories: ["Party"],
    },
    {
        id: 147,
        title_no: "Jeg har aldri lurt på om jeg var bifil.",
        title_en: "Never have I ever wondered if I was bisexual.",
        categories: ["Party"],
    },
    {
        id: 148,
        title_no: "Jeg har aldri flørtet med noen bare for å gjøre partneren min sjalu.",
        title_en: "Never have I ever flirted with someone just to make my partner jealous.",
        categories: ["Party"],
    },
    {
        id: 149,
        title_no: "Jeg har aldri deltatt i en orgie",
        title_en: "Never have I ever participated in an orgy",
        categories: ["Party", "Wild"],
    },
    {
        id: 150,
        title_no: "Jeg har aldri hatt et hemmelig forhold mens jeg var i et annet forhold.",
        title_en: "Never have I ever had a secret relationship while in another relationship.",
        categories: ["Party", "Wild"],
    },
    {
        id: 151,
        title_no: "Jeg har aldri prøvd å bytte prismerker i en butikk.",
        title_en: "Never have I ever tried to switch price tags in a store.",
        categories: ["Party"],
    },
    {
        id: 152,
        title_no: "Jeg har aldri sendt nudes.",
        title_en: "Never have I ever sent nudes.",
        categories: ["Party", "Wild"],
    },
    {
        id: 153,
        title_no: "Jeg har aldri hatt friends with benefits.",
        title_en: "Never have I ever had friends with benefits.",
        categories: ["Party", "Wild"],
    },
    {
        id: 154,
        title_no: "Jeg har aldri hatt en one-night stand.",
        title_en: "Never have I ever had a one-night stand.",
        categories: ["Party", "Wild"],
    },
    {
        id: 155,
        title_no: "Jeg har aldri pult noen dobbelt så gamle som meg.",
        title_en: "Never have I ever had sex with someone twice my age.",
        categories: ["Party", "Wild"],
    },
    {
        id: 156,
        title_no: "Jeg har aldri hatt en fantasi om en venns partner.",
        title_en: "Never have I ever had a fantasy about a friend's partner.",
        categories: ["Party", "Wild"],
    },
    {
        id: 157,
        title_no: "Jeg har aldri brukt sexleketøy.",
        title_en: "Never have I ever used a sex-toy.",
        categories: ["Party", "Wild"],
    },
    {
        id: 158,
        title_no: "Jeg har aldri tryna på isen på vei til skolen.",
        title_en: "Never have I ever fallen on the ice on the way to class.",
        categories: ["Party", "School"],
    },
    {
        id: 159,
        title_no: "Jeg har aldri sovna på vors.",
        title_en: "Never have I ever fallen asleep on vorspiel.",
        categories: ["Party"],
    },
    {
        id: 160,
        title_no: "Jeg har aldri meldt meg på ett reality program.",
        title_en: "Never have I ever signed meself up for a reality show.",
        categories: ["Party"],
    },
    {
        id: 161,
        title_no: "Jeg har aldri vurdert å bli med i en kult.",
        title_en: "Never have I ever considered joining a cult.",
        categories: ["Party"],
    },
    {
        id: 162,
        title_no: "Jeg har aldri svart på spørsmål på Stack Overflow.",
        title_en: "Never have I ever answered a question on Stack Overflow.",
        categories: ["Party"],
    },
    {
        id: 163,
        title_no: "Jeg har aldri dratt på bedpres bare for gratis mat.",
        title_en: "Never have I ever gone to a company presentation just for the free food.",
        categories: ["Party", "School"],
    },
    {
        id: 164,
        title_no: "Jeg har aldri blitt kasta ut fra Huset.",
        title_en: "Never have I ever been kicked out of Huset.",
        categories: ["Party", "NTNU"],
    },
    {
        id: 165,
        title_no: "Jeg har aldri kyssa noen for en drink på byen.",
        title_en: "Never have I ever kissed someone for a drink at the bar.",
        categories: ["Party", "Wild"],
    },
    {
        id: 166,
        title_no: "Jeg har aldri fått prikker på førerkortet.",
        title_en: "Never have I ever gotten points on my driver's license.",
        categories: ["Party"],
    },
    {
        id: 167,
        title_no: "Jeg har aldri krangla med en lærer.",
        title_en: "Never have I ever argued with a teacher.",
        categories: ["Party"],
    },
    {
        id: 168,
        title_no: "Jeg har aldri shama noen for noe jeg gjør selv.",
        title_en: "Never have I ever made fun of someone for something I do myself.",
        categories: ["Party"],
    },
    {
        id: 169,
        title_no: "Jeg har aldri stilt ett spørsmål på Reddit AITA.",
        title_en: "Never have I ever asked a question on Reddit AITA.",
        categories: ["Party"],
    },
    {
        id: 170,
        title_no: "Jeg har aldri stjålet noe på fylla.",
        title_en: "Never have I ever stolen something while drunk.",
        categories: ["Party"],
    },
    {
        id: 171,
        title_no: "Jeg har aldri stjålet noe på jobb.",
        title_en: "Never have I ever stolen something at work.",
        categories: ["Party"],
    },
    {
        id: 172,
        title_no: "Jeg har aldri stjålet noe fra kantina.",
        title_en: "Never have I ever stolen something from the canteen.",
        categories: ["Party"],
    },
    {
        id: 173,
        title_no: "Jeg har aldri sagt til sjefen at jeg er syk for å dra på fest.",
        title_en: "Never have I ever told my boss I was sick to go to a party.",
        categories: ["Party"],
    },
    {
        id: 174,
        title_no: "Jeg har aldri rømt fra politiet.",
        title_en: "Never have I ever run away from the police.",
        categories: ["Party"],
    },
    {
        id: 175,
        title_no: "Jeg har aldri brukt GPT til å jukse på en prøve.",
        title_en: "Never have I ever used GPT to cheat on a test.",
        categories: ["Party"],
    },
    {
        id: 176,
        title_no: "Jeg har aldri blitt nekta adgang på byen.",
        title_en: "Never have I ever been denied entry to a club.",
        categories: ["Party"],
    },
    {
        id: 177,
        title_no: "Jeg har aldri kasta opp mens jeg prøvde å chugge.",
        title_en: "Never have I ever thrown up while trying to chug.",
        categories: ["Party"],
    },
    {
        id: 178,
        title_no: "Jeg har aldri krasja.",
        title_en: "Never have I ever crashed.",
        categories: ["Party"],
    },
    {
        id: 179,
        title_no: "Jeg har aldri donert penger til et veldedig formål.",
        title_en: "Never have I ever donated money to a charity.",
        categories: ["Party"],
    },
    {
        id: 180,
        title_no: "Jeg har aldri donert penger til et politisk parti.",
        title_en: "Never have I ever donated money to a political party.",
        categories: ["Party"],
    },
    {
        id: 181,
        title_no: "Jeg har aldri googlet meg selv.",
        title_en: "Never have I ever googled myself.",
        categories: ["Party"],
    },
    {
        id: 182,
        title_no: "Jeg har aldri våkna med mat i hånda.",
        title_en: "Never have I ever woken up with food in my hand.",
        categories: ["Party"],
    },
    {
        id: 183,
        title_no: "Jeg har aldri sovna i en grøft.",
        title_en: "Never have I ever fallen asleep in a ditch.",
        categories: ["Party"],
    },
    {
        id: 184,
        title_no: "Jeg har aldri dratt hjem fra byen siden jeg ble lei av de jeg var med.",
        title_en: "Never have I ever left the bar cause I got tired of my friends.",
        categories: ["Party"],
    },
    {
        id: 185,
        title_no: "Jeg har aldri strippa for noen.",
        title_en: "Never have I ever stripped for someone.",
        categories: ["Party", "Wild"],
    },
    {
        id: 186,
        title_no: "Jeg har aldri strøket i ett fag.",
        title_en: "Never have I ever failed a course.",
        categories: ["Party", "School"],
    },
    {
        id: 187,
        title_no: "Jeg har aldri løyet om karakterene mine.",
        title_en: "Never have I ever lied about my grades.",
        categories: ["Party"],
    },
    {
        id: 188,
        title_no: "Jeg har aldri sett på porno.",
        title_en: "Never have I ever watched porn.",
        categories: ["Party", "Wild"],
    },
    {
        id: 189,
        title_no: "Jeg har aldri tissa på meg.",
        title_en: "Never have I ever wet meself.",
        categories: ["Party", "Wild"],
    },
    {
        id: 190,
        title_no: "Jeg har aldri trodd på synske.",
        title_en: "Never have I ever believed in psychics",
        categories: ["Party"],
    },
    {
        id: 191,
        title_no: "Jeg har aldri trodd på spøkelser eller lignende.",
        title_en: "Never have I ever believed in ghosts or similar.",
        categories: ["Party"],
    },
    {
        id: 192,
        title_no: "Jeg har aldri tatt kongla.",
        title_en: "Never have I ever had sex in a tree.",
        categories: ["Party", "Wild"],
    },
    {
        id: 193,
        title_no: "Jeg har aldri hatt en kjønnssykdom.",
        title_en: "Never have I ever had STDs.",
        categories: ["Party", "Wild"],
    },
    {
        id: 194,
        title_no: "Jeg har aldri catcha foreldrene mine i å pule.",
        title_en: "Never have I ever caught my parents making love.",
        categories: ["Party", "Wild"],
    },
    {
        id: 195,
        title_no: "Jeg har aldri onanert i dusjen.",
        title_en: "Never have I ever masturbated in the shower.",
        categories: ["Party", "Wild"],
    },
    {
        id: 196,
        title_no: "Jeg har aldri prøvd å stjele en bil.",
        title_en: "Never have I ever tried to steal a car.",
        categories: ["Party"],
    },
    {
        id: 197,
        title_no: "Jeg har aldri juksa på en prøve.",
        title_en: "Never have I ever cheated on a test.",
        categories: ["Party", "School"],
    },
    {
        id: 198,
        title_no: "Jeg har aldri sagt til noen at de er dårlige i senga.",
        title_en: "Never have I ever told someone they're bad in bed.",
        categories: ["Party"],
    },
    {
        id: 199,
        title_no: "Jeg har aldri vurdert å bytte kjønn.",
        title_en: "Never have I ever considered switching gender.",
        categories: ["Party"],
    },
    {
        id: 200,
        title_no: "Jeg har aldri tissa på ett offentlig sted.",
        title_en: "Never have I ever peed in a public place.",
        categories: ["Party"],
    },
    {
        id: 201,
        title_no: "Jeg har aldri tissa på meg i fylla.",
        title_en: "Never have I ever peed meself while drunk.",
        categories: ["Party", "Wild"],
    },
    {
        id: 202,
        title_no: "Jeg har aldri blitt pumpa.",
        title_en: "Never have I ever been pumped.",
        categories: ["Party"],
    },
    {
        id: 203,
        title_no: "Jeg har aldri pult i ett telt.",
        title_en: "Never have I ever had sex in a tent.",
        categories: ["Party", "Wild"],
    },
    {
        id: 204,
        title_no: "Jeg har aldri sulta siden jeg ikke hadde penger.",
        title_en: "Never have I ever starved because I didn't have money.",
        categories: ["Party"],
    },
    {
        id: 205,
        title_no: "Jeg har aldri prøvd å bli Tik-Tok kjendis.",
        title_en: "Never have I ever tried to become a Tik-Tok celebrity.",
        categories: ["Party"],
    },
    {
        id: 206,
        title_no: "Jeg har aldri klina med mer enn 5 stk på samme kveld.",
        title_en: "Never have I ever kissed more than 5 people in one night.",
        categories: ["Party", "Wild"],
    },
    {
        id: 207,
        title_no: "Jeg har aldri dratt på Tinder-date.",
        title_en: "Never have I ever been on a Tinder date.",
        categories: ["Party"],
    },
    {
        id: 208,
        title_no: "Jeg har aldri brukt mer enn to timer på do.",
        title_en: "Never have I ever spent more than two hours in the bathroom.",
        categories: ["Party"],
    },
    {
        id: 209,
        title_no: "Jeg har aldri sneket meg inn på ett utested.",
        title_en: "Never have I ever snuck into a bar.",
        categories: ["Party"],
    },
    {
        id: 210,
        title_no: "Jeg har aldri tjent penger på å selge nudes.",
        title_en: "Never have I ever made money selling nudes.",
        categories: ["Party", "Wild"],
    },
    {
        id: 211,
        title_no: "Jeg har aldri vært på en date med en som var mer enn 5 år eldre enn meg.",
        title_en: "Never have I ever been on a date with someone more than 5 years older than me.",
        categories: ["Party", "Wild"],
    },
    {
        id: 212,
        title_no: "Jeg har aldri vært på nach.",
        title_en: "Never have I ever been to a nachspiel.",
        categories: ["Party"],
    },
    {
        id: 213,
        title_no: "Jeg har aldri skada meg eller gjort noe dumt siden jeg ble redd for en edderkopp.",
        title_en: "Never have I ever hurt meself or done something stupid because I was scared of a spider.",
        categories: ["Party"],
    },
    {
        id: 214,
        title_no: "Jeg har aldri jugd. (alle som ikke drikker får 5 slurker siden det er 🧢)",
        title_en: "Never have I ever lied. (everyone who doesn't drink gets 5 sips since that is 🧢)",
        categories: ["Party"],
    },
    {
        id: 215,
        title_no: "Jeg har aldri sendt meldinger til mer enn 30 folk på en kveld.",
        title_en: "Never have I ever sent messages to more than 30 people in one night.",
        categories: ["Party", "Wild"],
    },
    {
        id: 216,
        title_no: "Jeg har aldri brukt mer enn 5000kr på takeaway samme måned.",
        title_en: "Never have I ever spent more than 5000kr on takeaway the same month.",
        categories: ["Party"],
    },
    {
        id: 217,
        title_no: "Jeg har aldri løpt maraton.",
        title_en: "Never have I ever ran a marathon.",
        categories: ["Party"],
    },
    {
        id: 218,
        title_no: "Jeg har aldri fått en parkeringsbot.",
        title_en: "Never have I ever gotten a parking ticket.",
        categories: ["Party"],
    },
    {
        id: 219,
        title_no: "Jeg har aldri gått meg vill på byen.",
        title_en: "Never have I ever gotten lost in the city.",
        categories: ["Party"],
    },
    {
        id: 220,
        title_no: "Jeg har aldri slått opp med noen over meldinger.",
        title_en: "Never have I ever broken up with someone over text.",
        categories: ["Party"],
    },
    {
        id: 221,
        title_no: "Jeg har aldri brutt loven.",
        title_en: "Never have I ever broken the law.",
        categories: ["Party"],
    },
    {
        id: 222,
        title_no: "Jeg har aldri hatt en one night stand med en kollega.",
        title_en: "Never have I ever had a one night stand with a colleague.",
        categories: ["Party", "Wild"],
    },
    {
        id: 223,
        title_no: "Jeg har aldri løyet om alderen min.",
        title_en: "Never have I ever lied about my age.",
        categories: ["Party"],
    },
    {
        id: 224,
        title_no: "Jeg har aldri blitt kastet ut av ett utested.",
        title_en: "Never have I ever been kicked out of a bar.",
        categories: ["Party"],
    },
    {
        id: 225,
        title_no: "Jeg har aldri spionert på en eks-kjæreste.",
        title_en: "Never have I ever spied on an ex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 226,
        title_no: "Jeg har aldri prøvd å stappe en deo, såpe, sminkeprodukt eller lignende i rumpa.",
        title_en: "Never have I ever tried to put deodorant, soap, makeup product or similar in my butt.",
        categories: ["Party", "Wild"],
    },
    {
        id: 227,
        title_no: "Jeg har aldri kyssa noen jeg ikke liker fordi jeg syntes synd på de.",
        title_en: "Never have I ever kissed someone I don't like because I felt sorry for them.",
        categories: ["Party", "Wild"],
    },
    {
        id: 228,
        title_no: "Jeg har aldri fingret / runket meg selv.",
        title_en: "Never have I ever fingered / jerked meself off.",
        categories: ["Party", "Wild"],
    },
    {
        id: 229,
        title_no: "Jeg har aldri måttet ringe hjem fra skolen siden jeg gjorde noe galt.",
        title_en: "Never have I ever had to call home from school since I did something wrong.",
        categories: ["Party", "Wild"],
    },
    {
        id: 230,
        title_no: "Jeg har aldri vært i mer enn 15 land.",
        title_en: "Never have I ever been to more than 15 countries.",
        categories: ["Party"],
    },
    {
        id: 231,
        title_no: "Jeg har aldri kjøpt en angrepille.",
        title_en: "Never have I bought a morning-pill.",
        categories: ["Party", "Wild"],
    },
    {
        id: 232,
        title_no: "Jeg har aldri gjort noe jeg angrer på mens jeg var full.",
        title_en: "Never have I ever done something I regret while drunk.",
        categories: ["Party"],
    },
    {
        id: 233,
        title_no: "Jeg har aldri smisket meg til en bedre karakter.",
        title_en: "Never have I ever flattered myself to a better grade.",
        categories: ["Party", "School"],
    },
    {
        id: 234,
        title_no: "Jeg har aldri tatt et bilde av meg selv på do.",
        title_en: "Never have I ever taken a picture of meself in the bathroom.",
        categories: ["Party"],
    },
    {
        id: 235,
        title_no: "Jeg har aldri hoppet fra 10 meteren.",
        title_en: "Never have I ever jumped from the 10-meter.",
        categories: ["Party"],
    },
    {
        id: 236,
        title_no: "Jeg har aldri tisset i dusjen.",
        title_en: "Never have I ever peed in the shower.",
        categories: ["Party"],
    },
    {
        id: 237,
        title_no: "Jeg har aldri besvimt.",
        title_en: "Never have I ever fainted.",
        categories: ["Party"],
    },
    {
        id: 238,
        title_no: "Jeg har aldri opplevd kjærlighet ved første blikk.",
        title_en: "Never have I ever experienced love at first sight.",
        categories: ["Party"],
    },
    {
        id: 239,
        title_no: "Jeg har aldri slått en jente.",
        title_en: "Never have I ever hit a girl.",
        categories: ["Party"],
    },
    {
        id: 240,
        title_no: "Jeg har aldri hatt et seriøst forhold.",
        title_en: "Never have I ever had a serious relationship.",
        categories: ["Party"],
    },
    {
        id: 241,
        title_no: "Jeg har aldri kjørt uten lappen.",
        title_en: "Never have I ever driven without a license.",
        categories: ["Party"],
    },
    {
        id: 242,
        title_no: "Jeg har aldri vært i USA.",
        title_en: "Never have I ever been to the United States.",
        categories: ["Party"],
    },
    {
        id: 243,
        title_no: "Jeg har aldri slikket en metallstolpe på vinteren.",
        title_en: "Never have I ever licked a metal pole during the winter.",
        categories: ["Party"],
    },
    {
        id: 244,
        title_no: "Jeg har aldri blitt satt i fyllearresten.",
        title_en: "Never have I ever been put in the drunk tank.",
        categories: ["Party"],
    },
    {
        id: 245,
        title_no: "Jeg har aldri vært i avhør.",
        title_en: "Never have I ever been interrogated.",
        categories: ["Party"],
    },
    {
        id: 246,
        title_no: "Jeg har aldri blitt spurt om jeg var jomfru av foreldrene mine.",
        title_en: "Never have I ever been asked if I was a virgin by my parents.",
        categories: ["Party"],
    },
    {
        id: 247,
        title_no: "Jeg har aldri tulleringt.",
        title_en: "Never have I ever prank called.",
        categories: ["Party"],
    },
    {
        id: 248,
        title_no: "Jeg har aldri sovnet på kino.",
        title_en: "Never have I ever fallen asleep at the movies.",
        categories: ["Party"],
    },
    {
        id: 249,
        title_no: "Jeg har aldri tissa på noen.",
        title_en: "Never have I ever peed on someone.",
        categories: ["Party", "Wild"],
    },
    {
        id: 250,
        title_no: "Jeg har aldri blitt kastet ut av en konsert.",
        title_en: "Never have I ever been kicked out of a concert.",
        categories: ["Party"],
    },
    {
        id: 251,
        title_no: "Jeg har aldri bæsjet ute.",
        title_en: "Never have I ever pooped outdoors.",
        categories: ["Party"],
    },
    {
        id: 252,
        title_no: "Jeg har aldri vært matforgiftet.",
        title_en: "Never have I ever been food poisoned.",
        categories: ["Party"],
    },
    {
        id: 253,
        title_no: "Jeg har aldri fått en venn til å være utro.",
        title_en: "Never have I ever gotten a friend to cheat.",
        categories: ["Party"],
    },
    {
        id: 254,
        title_no: "Jeg har aldri blitt kalt en tease.",
        title_en: "Never have I ever been called a tease.",
        categories: ["Party"],
    },
    {
        id: 255,
        title_no: "Jeg har aldri skrevet en jodel.",
        title_en: "Never have I ever written a jodel.",
        categories: ["Party"],
    },
    {
        id: 256,
        title_no: "Jeg har aldri spist blekksprut.",
        title_en: "Never have I ever eaten squid.",
        categories: ["Party"],
    },
    {
        id: 257,
        title_no: "Jeg har aldri sovnet på skolen.",
        title_en: "Never have I ever fallen asleep in class.",
        categories: ["Party"],
    },
    {
        id: 258,
        title_no: "Jeg har aldri sett Harry Potter.",
        title_en: "Never have I ever seen Harry Potter.",
        categories: ["Party"],
    },
    {
        id: 259,
        title_no: "Jeg har aldri skutt med en ekte pistol.",
        title_en: "Never have I ever shot with a real gun.",
        categories: ["Party"],
    },
    {
        id: 260,
        title_no: "Jeg har aldri mistet telefonen i toalettet.",
        title_en: "Never have I ever dropped my phone in the toilet.",
        categories: ["Party"],
    },
    {
        id: 261,
        title_no: "Jeg har aldri blitt kalt inn til rektor.",
        title_en: "Never have I ever been called in to the principals office.",
        categories: ["Party"],
    },
    {
        id: 262,
        title_no: "Jeg har aldri kastet opp blod.",
        title_en: "Never have I ever thrown up blood.",
        categories: ["Party"],
    },
    {
        id: 263,
        title_no: "Jeg har aldri sovnet på jobb.",
        title_en: "Never have I ever fallen asleep at work.",
        categories: ["Party"],
    },
    {
        id: 264,
        title_no: "Jeg har aldri blitt sendt på gangen av læreren.",
        title_en: "Never have I ever been sent out of the classroom by the teacher.",
        categories: ["Party"],
    },
    {
        id: 265,
        title_no: "Jeg har aldri spist en hel grandis alene.",
        title_en: "Never have I ever eaten a whole grandiosa by meself.",
        categories: ["Party"],
    },
    {
        id: 266,
        title_no: "Jeg har aldri våknet av en bøtte vann i ansiktet.",
        title_en: "Never have I ever woken up to a bucket of water in my face.",
        categories: ["Party"],
    },
    {
        id: 267,
        title_no: "Jeg har aldri hoppet ut av en bil i fart.",
        title_en: "Never have I ever jumped out of a moving car.",
        categories: ["Party"],
    },
    {
        id: 268,
        title_no: "Jeg har aldri sagt til noen at jeg elsker de uten å mene det.",
        title_en: "Never have I ever told someone I love them without meaning it.",
        categories: ["Party"],
    },
    {
        id: 269,
        title_no: "Jeg har aldri knust en TV",
        title_en: "Never have I ever broken a TV",
        categories: ["Party"],
    },
    {
        id: 270,
        title_no: "Jeg har aldri vært forelsket i noen i dette rommet.",
        title_en: "Never have I ever been in love with someone in this room.",
        categories: ["Party"],
    },
    {
        id: 271,
        title_no: "Jeg har aldri bestilt noe fra utlandet.",
        title_en: "Never have I ever ordered something from abroad.",
        categories: ["Party"],
    },
    {
        id: 272,
        title_no: "Jeg har aldri spydd i vasken på fest.",
        title_en: "Never have I ever thrown up in the sink at a party.",
        categories: ["Party"],
    },
    {
        id: 273,
        title_no: "Jeg har aldri sovnet på kjøkkenet.",
        title_en: "Never have I ever fallen asleep in the kitchen.",
        categories: ["Party"],
    },
    {
        id: 274,
        title_no: "Jeg har aldri postet et bilde i sosiale medier for å gjøre en person sjalu.",
        title_en: "Never have I ever posted a picture on social media to make someone jealous.",
        categories: ["Party"],
    },
    {
        id: 275,
        title_no: "Jeg har aldri sjekket opp noen jeg visste var i et forhold.",
        title_en: "Never have I ever hit on someone I knew was in a relationship.",
        categories: ["Party"],
    },
    {
        id: 276,
        title_no: "Jeg har aldri gått på kino alene.",
        title_en: "Never have I ever gone to the movies alone.",
        categories: ["Party"],
    },
    {
        id: 277,
        title_no: "Jeg har aldri kysset i regnet.",
        title_en: "Never have I ever kissed in the rain.",
        categories: ["Party"],
    },
    {
        id: 278,
        title_no: "Jeg har aldri slått noen til blods.",
        title_en: "Never have I ever beaten someone to blood.",
        categories: ["Party"],
    },
    {
        id: 279,
        title_no: "Jeg har aldri bevisst postet et bilde der jeg selv var fin, men vennen min var stygg.",
        title_en: "Never have I ever knowingly posted a picture where I looked good, but my friend looked ugly.",
        categories: ["Party"],
    },
    {
        id: 280,
        title_no: "Jeg har aldri sovet i mer enn 14 timer.",
        title_en: "Never have I ever slept for more than 14 hours.",
        categories: ["Party"],
    },
    {
        id: 281,
        title_no: "Jeg har aldri spydd i en taxi.",
        title_en: "Never have I ever thrown up in a taxi.",
        categories: ["Party"],
    },
    {
        id: 282,
        title_no: "Jeg har aldri tisset i et svømmebasseng.",
        title_en: "Never have I ever peed in a swimming pool.",
        categories: ["Party"],
    },
    {
        id: 283,
        title_no: "Jeg har aldri prøvd å skrive min egen sang.",
        title_en: "Never have I ever tried to write my own song.",
        categories: ["Party"],
    },
    {
        id: 284,
        title_no: "Jeg har aldri blitt utvist fra skolen.",
        title_en: "Never have I ever been expelled from school.",
        categories: ["Party"],
    },
    {
        id: 285,
        title_no: "Jeg har aldri vært på TV.",
        title_en: "Never have I ever been on TV.",
        categories: ["Party"],
    },
    {
        id: 286,
        title_no: "Jeg har aldri drept et dyr.",
        title_en: "Never have I ever killed an animal.",
        categories: ["Party"],
    },
    {
        id: 287,
        title_no: "Jeg har aldri tissa opp ned.",
        title_en: "Never have I ever peed upside down.",
        categories: ["Party"],
    },
    {
        id: 288,
        title_no: "Jeg har aldri vært utro.",
        title_en: "Never have I ever cheated.",
        categories: ["Party"],
    },
    {
        id: 289,
        title_no: "Jeg har aldri laget en sex video.",
        title_en: "Never have I ever made a sex tape.",
        categories: ["Party", "Wild"],
    },
    {
        id: 290,
        title_no: "Jeg har aldri hatt sex med en svenske.",
        title_en: "Never have I ever had sex with a Swede.",
        categories: ["Party", "Wild"],
    },
    {
        id: 291,
        title_no: "Jeg har aldri hatt sex med noen fra INGA.",
        title_en: "Never have I ever had sex with someone from INGA.",
        categories: ["Party", "NTNU", "Wild"],
    },
    {
        id: 292,
        title_no: "Jeg har aldri hatt rollespill på soverommet.",
        title_en: "Never have I ever had roleplay in the bedroom.",
        categories: ["Party", "Wild"],
    },
    {
        id: 293,
        title_no: "Jeg har aldri hatt sex på gulvet.",
        title_en: "Never have I ever had sex on the floor.",
        categories: ["Party", "Wild"],
    },
    {
        id: 294,
        title_no: "Jeg har aldri brukt sexleketøy på meg selv alene.",
        title_en: "Never have I ever used sex toys on myself alone.",
        categories: ["Party", "Wild"],
    },
    {
        id: 295,
        title_no: "Jeg har aldri onanert det motsatte kjønn.",
        title_en: "Never have I ever masturbated the opposite gender.",
        categories: ["Party", "Wild"],
    },
    {
        id: 296,
        title_no: "Jeg har aldri vært på strippeklubb.",
        title_en: "Never have I ever been to a strip club.",
        categories: ["Party", "Wild"],
    },
    {
        id: 297,
        title_no: "Jeg har aldri hatt sex med kostyme.",
        title_en: "Never have I ever had sex in a costume.",
        categories: ["Party", "Wild"],
    },
    {
        id: 298,
        title_no: "Jeg har aldri hatt lyst på noen som sitter i dette rommet.",
        title_en: "Never have I ever wanted someone in this room.",
        categories: ["Party", "Wild"],
    },
    {
        id: 299,
        title_no: "Jeg har aldri hatt sex med mer enn 2 personer på samme kveld.",
        title_en: "Never have I ever had sex with more than 2 people in one night.",
        categories: ["Party", "Wild"],
    },
    {
        id: 300,
        title_no: "Jeg har aldri sagt feil navn under sex.",
        title_en: "Never have I ever said the wrong name during intercourse.",
        categories: ["Party", "Wild"],
    },
    {
        id: 301,
        title_no: "Jeg har aldri hatt sex på en trampoline.",
        title_en: "Never have I ever had sex on a trampoline.",
        categories: ["Party", "Wild"],
    },
    {
        id: 302,
        title_no: "Jeg har aldri gitt eller fått en footjob.",
        title_en: "Never have I ever given or received a footjob.",
        categories: ["Party", "Wild"],
    },
    {
        id: 303,
        title_no: "Jeg har aldri hatt sex i en trapp.",
        title_en: "Never have I ever had sex in a staircase.",
        categories: ["Party", "Wild"],
    },
    {
        id: 304,
        title_no: "Jeg har aldri gått et helt år uten sex etter jeg mistet jomfrudommen.",
        title_en: "Never have I ever gone a whole year without sex after losing my virginity.",
        categories: ["Party", "Wild"],
    },
    {
        id: 305,
        title_no: "Jeg har aldri våknet opp til oralsex.",
        title_en: "Never have I ever woken up to oral sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 306,
        title_no: "Jeg har aldri fått anal uten vilje.",
        title_en: "Never have I ever gotten anal unwillingly.",
        categories: ["Party", "Wild"],
    },
    {
        id: 307,
        title_no: "Jeg har aldri slikket mine egne pupper.",
        title_en: "Never have I ever licked my own nipples.",
        categories: ["Party", "Wild"],
    },
    {
        id: 308,
        title_no: "Jeg har aldri fått oralsex i dusjen.",
        title_en: "Never have I ever gotten oral sex in the shower.",
        categories: ["Party", "Wild"],
    },
    {
        id: 309,
        title_no: "Jeg har aldri hatt FaceTime sex.",
        title_en: "Never have I ever had FaceTime sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 310,
        title_no: "Jeg har aldri kjøpt sexy undertøy og brukt det.",
        title_en: "Never have I ever bought sexy lingerie and worn it.",
        categories: ["Party", "Wild"],
    },
    {
        id: 311,
        title_no: "Jeg har aldri hatt sex mens noen andre så på.",
        title_en: "Never have I ever had sex while someone else watched.",
        categories: ["Party", "Wild"],
    },
    {
        id: 312,
        title_no: "Jeg har aldri onanert på skolen.",
        title_en: "Never have I ever masturbated at school.",
        categories: ["Party", "Wild"],
    },
    {
        id: 313,
        title_no: "Jeg har aldri filmet at jeg har sex.",
        title_en: "Never have I ever recorded myself having sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 314,
        title_no: "Jeg har aldri hatt sex i et badekar.",
        title_en: "Never have I ever had sex in a bathtub.",
        categories: ["Party", "Wild"],
    },
    {
        id: 315,
        title_no: "Jeg har aldri tatt flere personers jomfrudom.",
        title_en: "Never have I ever taken multiple people's virginity.",
        categories: ["Party", "Wild"],
    },
    {
        id: 316,
        title_no: "Jeg har aldri onanert i naturen.",
        title_en: "Never have I ever masturbated in nature.",
        categories: ["Party", "Wild"],
    },
    {
        id: 317,
        title_no: "Jeg har aldri gitt noen en lapdance.",
        title_en: "Never have I ever given someone a lapdance.",
        categories: ["Party", "Wild"],
    },
    {
        id: 318,
        title_no: "Jeg har aldri skulket skolen for sex.",
        title_en: "Never have I ever skipped class for sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 319,
        title_no: "Jeg har aldri hatt sex i en sofa.",
        title_en: "Never have I ever had sex in a sofa.",
        categories: ["Party", "Wild"],
    },
    {
        id: 320,
        title_no: "Jeg har aldri hatt en våt drøm.",
        title_en: "Never have I ever had a wet dream.",
        categories: ["Party", "Wild"],
    },
    {
        id: 329,
        title_no: "Jeg har aldri hatt en walk of shame.",
        title_en: "Never have I ever had a walk of shame.",
        categories: ["Party"],
    },
    {
        id: 330,
        title_no: "Jeg har aldri brukt glidemiddel når jeg har onanert.",
        title_en: "Never have I ever used lubrication during masturbation.",
        categories: ["Party", "Wild"],
    },
    {
        id: 339,
        title_no: "Jeg har aldri kjørt brannbil",
        title_en: "Never have I ever driven a fire truck",
        categories: ["Party", "Wild"],
    },
    {
        id: 340,
        title_no: "Jeg har aldri nakenbadet ute.",
        title_en: "Never have I ever gone skinny dipping.",
        categories: ["Party", "Wild"],
    },
    {
        id: 341,
        title_no: "Jeg har aldri gitt noen et sexleketøy i gave.",
        title_en: "Never have I ever gifted someone a sex toy.",
        categories: ["Party", "Wild"],
    },
    {
        id: 342,
        title_no: "Jeg har aldri hatt sex i foreldrene mine sin seng.",
        title_en: "Never have I ever had sex in my parents bed.",
        categories: ["Party", "Wild"],
    },
    {
        id: 343,
        title_no: "Jeg har aldri hatt sex med noen uten å huske det.",
        title_en: "Never have I ever had sex with someone without knowing it.",
        categories: ["Party", "Wild"],
    },
    {
        id: 344,
        title_no: "Jeg har aldri hatt bind for øynene under sex.",
        title_en: "Never have I ever been blindfolded during sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 345,
        title_no: "Jeg har aldri løyet om meg selv for å få meg noe.",
        title_en: "Never have I ever lied about meself for sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 346,
        title_no: "Jeg har aldri fått betalt for å ha sex.",
        title_en: "Never have I ever been paid to have sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 347,
        title_no: "Jeg har aldri tatt viagra.",
        title_en: "Never have I ever taken viagra.",
        categories: ["Party", "Wild"],
    },
    {
        id: 348,
        title_no: "Jeg har aldri onanert mens jeg har tenkt på noen her.",
        title_en: "Never have I ever masturbated while thinking about someone here.",
        categories: ["Party", "Wild"],
    },
    {
        id: 349,
        title_no: "Jeg har aldri flashet eller blottet for noen.",
        title_en: "Never have I ever flashed or exposed meself to someone.",
        categories: ["Party", "Wild"],
    },
    {
        id: 350,
        title_no: "Jeg har aldri løyet om å være jomfru.",
        title_en: "Never have I ever lied about being a virgin.",
        categories: ["Party", "Wild"],
    },
    {
        id: 351,
        title_no: "Jeg har aldri onanert på skolens toaletter.",
        title_en: "Never have I ever masturbated in the school's bathroom.",
        categories: ["Party", "Wild"],
    },
    {
        id: 352,
        title_no: "Jeg har aldri mistet jomfrudommen på noe annet enn en seng.",
        title_en: "Never have I ever lost my virginity on anything other than a bed.",
        categories: ["Party", "Wild"],
    },
    {
        id: 353,
        title_no: "Jeg har aldri brukt vibrator",
        title_en: "Never have I ever used a vibrator.",
        categories: ["Party", "Wild"],
    },
    {
        id: 354,
        title_no: "Jeg har aldri hatt sex med det samme kjønn.",
        title_en: "Never have I ever had sex with the same gender.",
        categories: ["Party", "Wild"],
    },
    {
        id: 355,
        title_no: "Jeg har aldri fantasert om sex med noen i dette rommet.",
        title_en: "Never have I ever fantasized about sex with someone in this room.",
        categories: ["Party", "Wild"],
    },
    {
        id: 356,
        title_no: "Jeg har aldri drømt at jeg har sex.",
        title_en: "Never have I ever dreamt that I was having sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 357,
        title_no: "Jeg har aldri brukt håndjern i sengen.",
        title_en: "Never have I ever used handcuffs in bed.",
        categories: ["Party", "Wild"],
    },
    {
        id: 358,
        title_no: "Jeg har aldri sovnet under sex.",
        title_en: "Never have I ever fallen asleep during sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 359,
        title_no: "Jeg har aldri slikket nutella eller krem av en annen person.",
        title_en: "Never have I ever licked nutella or cream off another person.",
        categories: ["Party", "Wild"],
    },
    {
        id: 360,
        title_no: "Jeg har aldri hatt sex i en sovepose.",
        title_en: "Never have I ever had sex in a sleeping bag.",
        categories: ["Party", "Wild"],
    },
    {
        id: 361,
        title_no: "Jeg har aldri løyet om hvor mange jeg har hatt sex med.",
        title_en: "Never have I ever lied about how many people I've had sex with.",
        categories: ["Party", "Wild"],
    },
    {
        id: 362,
        title_no: "Jeg har aldri ombestemt meg om å ha sex med noen etter å ha sett de naken.",
        title_en: "Never have I ever changed my mind about having sex with someone after seeing them naked.",
        categories: ["Party", "Wild"],
    },
    {
        id: 363,
        title_no: "Jeg har aldri brukt beskyttelse.",
        title_en: "Never have I ever wore protection.",
        categories: ["Party", "Wild"],
    },
    {
        id: 364,
        title_no: "Jeg har aldri hatt sex med noen i dette rommet.",
        title_en: "Never have I ever had sex with someone in this room.",
        categories: ["Party", "Wild"],
    },
    {
        id: 365,
        title_no: "Jeg har aldri twerket på byen.",
        title_en: "Never have I ever twerked in public.",
        categories: ["Party", "Wild"],
    },
    {
        id: 366,
        title_no: "Jeg har aldri blitt fersket i å ha sex i en bil.",
        title_en: "Never have I ever been caught having sex in a car.",
        categories: ["Party", "Wild"],
    },
    {
        id: 367,
        title_no: "Jeg har aldri vært misfornøyd etter sex.",
        title_en: "Never have I ever been dissatisfied after sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 368,
        title_no: "Jeg har aldri hatt sex i dusjen.",
        title_en: "Never have I ever had sex in the shower.",
        categories: ["Party", "Wild"],
    },
    {
        id: 369,
        title_no: "Jeg har aldri faket at jeg har kommet.",
        title_en: "Never have I ever faked an orgasm.",
        categories: ["Party", "Wild"],
    },
    {
        id: 370,
        title_no: "Jeg har aldri onanert med en frukt.",
        title_en: "Never have I ever masturbated with a fruit.",
        categories: ["Party", "Wild"],
    },
    {
        id: 371,
        title_no: "Jeg har aldri hatt sex i et familieselskap.",
        title_en: "Never have I ever had sex during a family gathering.",
        categories: ["Party", "Wild"],
    },
    {
        id: 372,
        title_no: "Jeg har aldri brukt pisk i sengen.",
        title_en: "Never have I ever used a whip in bed.",
        categories: ["Party", "Wild"],
    },
    {
        id: 373,
        title_no: "Jeg har aldri dusjet med minst to personer i samme dusj.",
        title_en: "Never have I ever showered with at least two people in the same shower.",
        categories: ["Party", "Wild"],
    },
    {
        id: 374,
        title_no: "Jeg har aldri vært naken på offentlig sted.",
        title_en: "Never have I ever been naked in public.",
        categories: ["Party", "Wild"],
    },
    {
        id: 375,
        title_no: "Jeg har aldri hatt sex på kjøkkenet.",
        title_en: "Never have I ever had sex in the kitchen.",
        categories: ["Party", "Wild"],
    },
    {
        id: 376,
        title_no: "Jeg har aldri spurt noen hva de heter under sex.",
        title_en: "Never have I ever asked someone what their name during sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 377,
        title_no: "Jeg har aldri hatt firkant.",
        title_en: "Never have I ever had a foursome.",
        categories: ["Party", "Wild"],
    },
    {
        id: 378,
        title_no: "Jeg har aldri løpt naken ute.",
        title_en: "Never have I ever ran naked outside.",
        categories: ["Party", "Wild"],
    },
    {
        id: 379,
        title_no: "Jeg har aldri googlet etter sex-stillinger.",
        title_en: "Never have I ever googled for sex positions.",
        categories: ["Party", "Wild"],
    },
    {
        id: 380,
        title_no: "Jeg har aldri brukt noen andre sitt sexleketøy.",
        title_en: "Never have I ever used someone else's sex toy.",
        categories: ["Party", "Wild"],
    },
    {
        id: 381,
        title_no: "Jeg har aldri vært kåt på moren eller faren til vennen min.",
        title_en: "Never have I ever been horny on the mother or father of my friend.",
        categories: ["Party", "Wild"],
    },
    {
        id: 382,
        title_no: "Jeg har aldri målt meg selv der nede.",
        title_en: "Never have I ever measured my privates.",
        categories: ["Party", "Wild"],
    },
    {
        id: 383,
        title_no: "Jeg har aldri hatt en pulevenn.",
        title_en: "Never have I ever had a fuck-mate.",
        categories: ["Party", "Wild"],
    },
    {
        id: 384,
        title_no: "Jeg har aldri blitt glad eller overrasket over å ha mensen.",
        title_en: "Never have I ever been happy or surprised over getting my menstruation.",
        categories: ["Party", "Wild"],
    },
    {
        id: 385,
        title_no: "Jeg har aldri fingret i noen andre sitt hus.",
        title_en: "Never have I ever fingered in someone elses house.",
        categories: ["Party", "Wild"],
    },
    {
        id: 386,
        title_no: "Jeg har aldri blitt betalt for å strippe.",
        title_en: "Never have I ever been paid to strip.",
        categories: ["Party", "Wild"],
    },
    {
        id: 387,
        title_no: "Jeg har aldri sett noen naken uten at det var planlagt.",
        title_en: "Never have I ever seen someone naked without it being planned.",
        categories: ["Party", "Wild"],
    },
    {
        id: 388,
        title_no: "Jeg har aldri hatt flere pulevenner samtidig.",
        title_en: "Never have I ever had multiple fuck-friends at once.",
        categories: ["Party", "Wild"],
    },
    {
        id: 389,
        title_no: "Jeg har aldri latet som jeg har snakket i telefonen.",
        title_en: "Never have I ever pretended to be talking on my phone.",
        categories: ["Party"],
    },
    {
        id: 390,
        title_no: "Jeg har aldri knust skjermen på telefonen min.",
        title_en: "Never have I ever broken the screen on my phone.",
        categories: ["Party"],
    },
    {
        id: 391,
        title_no: "Jeg har aldri blitt tatt for å jukse på en prøve eller eksamen.",
        title_en: "Never have I ever been caught cheating on a test or exam.",
        categories: ["Party"],
    },
    {
        id: 392,
        title_no: "Jeg har aldri fått en bot.",
        title_en: "Never have I ever recieved a fine.",
        categories: ["Party"],
    },
    {
        id: 393,
        title_no: "Jeg har aldri onanert det samme kjønn.",
        title_en: "Never have I ever masturbated the same gender.",
        categories: ["Party", "Wild"],
    },
    {
        id: 394,
        title_no: "Jeg har aldri brukket noe.",
        title_en: "Never have I ever broken a bone.",
        categories: ["Party"],
    },
    {
        id: 395,
        title_no: "Jeg har aldri skulket",
        title_en: "Never have I ever skipped school",
        categories: ["Party"],
    },
    {
        id: 396,
        title_no: "Jeg har aldri hatt en Valentinsdate",
        title_en: "Never have I ever had a Valentine's date",
        categories: ["Party"],
    },
]

const categories = ["Gaming", "Party", "School", "Wild", "NTNU"]

export { categories }
export default NeverHaveIEver
